USE Films
-- Drop all tables
DROP TABLE IF EXISTS MuzykaWFilmie;
DROP TABLE IF EXISTS MuzykiFilmowe;
DROP TABLE IF EXISTS Posiadanie_Przez_Aktora;
DROP TABLE IF EXISTS Posiadanie_Przez_Re¿ysera;
DROP TABLE IF EXISTS Posiadanie_Przez_Film;
DROP TABLE IF EXISTS OcenyFilmu;
DROP TABLE IF EXISTS Recenzenci;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Aktorzy;
DROP TABLE IF EXISTS Tworzenie;
DROP TABLE IF EXISTS Re¿yserzy;
DROP TABLE IF EXISTS LudzieKina;
DROP TABLE IF EXISTS Nagrody;
DROP TABLE IF EXISTS Wytwarzanie;
DROP TABLE IF EXISTS StudiaFilmowe;
DROP TABLE IF EXISTS NalezyDo;
DROP TABLE IF EXISTS Gatunki;
DROP TABLE IF EXISTS Filmy;
